import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yuhei's Tech Blog",
  description: "Generated by yuhei",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <div className="mx-auto flex w-[550px] flex-col sm:container lg:w-[950px]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
